class Node
  VALID_RANGE: Range[Float]

  attr_reader weight: Float

  attr_reader bias: Float

  attr_reader value: Float | nil

  def self.activation_function: (Float x) -> Float

  class PropertyOutsideRangeError < StandardError
  end

  def initialize: (?weight: Float, ?bias: Float) -> void

  def activate: (*Node inputs) -> Float
end
